### ISSUE TITLE
Unexpected search results with partial matches of multi-word tags

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb#1200] opened 2024-12-06 15:24 UTC
If you go to IFDB and do the search  `-tag:disturbing`, some results include

> tags matched:

like this:

> Slouching Towards Bedlam
> by Star Foster and Daniel Ravipinto
> 2003
> Tags matched: disturbing themes
> (214 ratings)
 
If the term "disturbing" matches "disturbing themes," then why is this game included in search results?

On the other hand, if the tag doesn't match, then why does it say "tags matched"?

I'm not sure how search is intended to handle partial matches like this, but the "tags matched" thing kind of makes it look like it was trying to include rather than exclude the tag.

**Comment by salty-horse** [comment] 2024-12-06 15:29
I think it's a duplicate of #457

**Comment by alice-blue** [comment] 2024-12-06 15:32
It might be a little different, in that this is a search that tries to exclude rather than include tags.

**Comment by salty-horse** [comment] 2024-12-06 17:55
You're right. So the fix is to not run the "Tags matched" check for negative-match filters.

**Closed** 2024-12-19 00:20 UTC
