### ISSUE TITLE
"Episode 1 of (series)" links to sorted-by-rating, not time

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifdb#366] opened 2024-10-05 18:16 UTC
https://ifdb.org/viewgame?id=tyu4zalevqkvujk4 if you click on "1 of 5 in Unnkulia" sends us to this page

https://ifdb.org/search?searchfor=series:the+Unnkulian+series

But the problem is, it's not first in the default list, and it feels like it should be.

Can we actually sort by entry number? e.g. "sortby=seriesnum" even if it is hidden?

And if that's not a possibility, can we default to order of publication e.g.

https://ifdb.org/search?sortby=old&searchfor=series%3Athe+Unnkulian+series (sortby=old& added)?

**Comment by dfabulich** [comment] 2024-10-11 18:44
Duplicate of #417

**Closed** 2024-10-11 18:44 UTC
